# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationreceiver',
            name='messenger_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='notificationreceiver',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
