# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera_panel', '0003_auto_20180115_1446'),
        ('notifications', '0002_auto_20180116_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notification_type', models.IntegerField(choices=[(0, 'non_specified'), (1, 'motion_alert')], default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera_panel.Camera')),
            ],
        ),
    ]
