# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera_panel', '0002_auto_20180115_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='datetime',
            new_name='datetime_started',
        ),
    ]
